apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowrie-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cowrie
  template:
    metadata:
      labels:
        app: cowrie
    spec:
      containers:
      - name: cowrie
        image: cowrie/cowrie:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 2222

        volumeMounts:
        - name: honeyfs
          mountPath: /cowrie/cowrie/honeyfs

      volumes:
      - name: honeyfs
        hostPath:
          path: /home/ubuntu/cowrie-fakefs
          type: Directory
